# Generated by Django 3.0.1 on 2020-02-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusclePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('difficulty', models.CharField(choices=[('łatwe', 'łatwe'), ('średnie', 'średnie'), ('trudne', 'trudne')], default='łatwe', max_length=7)),
                ('muscles', models.ManyToManyField(to='user_panel.MusclePart')),
            ],
        ),
    ]
